### ISSUE TITLE
It's no longer working

### ISSUE THREAD

**Issue by climbzona** [mgualdron/TablePlus#1]
This ext is amazing. I just started using it but it recently stopped pasting into Jira. A number of my coworkers attempted to install but it doesn't work for them also.

Just want to let you know.

Chrome Version 53.0.2785.116 (64-bit)
Mac OS 10.11.6

Happy to write a review when it's back up and running. Thanks for the work you put in on this.

**Comment by mgualdron** [comment]
I will try to reproduce the issue, and go from there.  Thanks for trying it out and letting me know.

**Comment by mgualdron** [comment]
I have released version 0.0.6 of TablePlus, which fixes this issue.  It is now out on the [Chrome Web Store](https://chrome.google.com/webstore/detail/tableplus/fhgekekdakigpdfdppllmpackoklhklb).
I tested it on Mac OS 10.11.6, Windows 7, and Ubuntu Linux 14.04, all with version 53.0.2785116 (64-bit) of Google chrome.

**Comment by climbzona** [comment]
Thanks Miguel! This is great!

I'm happy to write a positive rating.

**Comment by mgualdron** [comment]
That would be great.  I'm glad you find it useful.
